name: "🐛 Bug Report"
description: Report something that isn't working as expected.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please provide enough detail to help us fix it.
  - type: input
    id: title
    attributes:
      label: Bug summary
      placeholder: e.g. "CLI crashes on empty input"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include commands or inputs that reproduce the issue.
      placeholder: |
        1. Run `deno task dev`
        2. Enter input: ...
        3. See error: ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      placeholder: e.g. "It should skip empty input instead of crashing."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and environment
      description: Paste any error logs and mention your OS, Deno version, and provider (ollama, OpenAI, etc.)
      placeholder: |
        Arch Linux, Deno 2.2.1, ollama 0.1.29
        Error:
        ```
        ...
        ```
    validations:
      required: false
