blank_issues_enabled: false
contact_links:
  - name: 💬 Ask a Question or Get Help
    url: https://github.com/AhmedOsman101/commit-sage-cli/discussions
    about: Use GitHub Discussions to ask questions, suggest ideas, or get support.
  - name: 📧 Email the Maintainer
    url: mailto:ahmad.ali.othman@outlook.com
    about: Prefer private or direct communication? Email me.

